; common.inc
; Thomas J. Armytage 2026 ( https://github.com/tommojphillips/ )
;

extern KCODE                            ; Kernel code segment
extern KDATA                            ; Kernel data segment
extern KSTACK                           ; Kernel stack segment
extern KTSS                             ; Kernel tss

extern UCODE                            ; User code segment
extern UDATA                            ; User data segment
extern USTACK                           ; User stack segment
