; common.inc
; Thomas J. Armytage 2026 ( https://github.com/tommojphillips/ )
;

extern KCODE                            ; Kernelspace code segment
extern KDATA                            ; Kernelspace data segment
extern KSTACK                           ; Kernelspace stack segment
extern KTSS                             ; Kernelspace tss

extern UCODE                            ; Userspace code segment
extern UDATA                            ; Userspace data segment
extern USTACK                           ; Userspace stack segment
